// Browser integration checks using the Chrome already installed on this Mac.
// No downloaded packages or browser binaries are required.
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const { createChessServer } = require('../server.cjs');
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

async function main() {
  const folder = fs.mkdtempSync(path.join(os.tmpdir(), 'chess-browser-'));
  const server = createChessServer({ dataDir: path.join(folder, 'data') });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const base = `http://127.0.0.1:${server.address().port}`;
  const chrome = spawn(process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', ['--headless=new', '--remote-debugging-port=0', '--user-data-dir='+path.join(folder,'profile'), '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio:['ignore','ignore','pipe'] });
  let ws;
  try {
    const endpoint = await new Promise((resolve,reject) => {
      let stderr=''; const timeout=setTimeout(()=>reject(Error('Chrome startup timed out')),15000);
      chrome.once('error',reject);
      chrome.stderr.on('data',chunk=>{stderr+=chunk;const m=stderr.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(m){clearTimeout(timeout);resolve(m[1])}});
      chrome.once('exit',code=>{clearTimeout(timeout);reject(Error('Chrome exited '+code+' '+stderr.slice(-1000)))});
    });
    ws = new WebSocket(endpoint);
    await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true})});
    let id=0; const pending=new Map(), errors=[];
    ws.addEventListener('message',event=>{const m=JSON.parse(event.data);if(m.id){const p=pending.get(m.id);if(p){clearTimeout(p.timer);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result)}}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||m.params.exceptionDetails.text)});
    function send(method,params={},sessionId){return new Promise((resolve,reject)=>{const requestId=++id;const timer=setTimeout(()=>{pending.delete(requestId);reject(Error('CDP timeout: '+method))},15000);pending.set(requestId,{resolve,reject,timer});ws.send(JSON.stringify({id:requestId,method,params,...(sessionId?{sessionId}:{})}))})}
    async function page(){const context=await send('Target.createBrowserContext');const target=await send('Target.createTarget',{url:'about:blank',browserContextId:context.browserContextId});const {sessionId}=await send('Target.attachToTarget',{targetId:target.targetId,flatten:true});await send('Runtime.enable',{},sessionId);await send('Page.enable',{},sessionId);await send('Page.navigate',{url:base},sessionId);const p={sessionId,async eval(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true},sessionId);if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value},async until(expression){for(let i=0;i<120;i++){if(await this.eval(expression))return;await delay(50)}throw Error('Timed out: '+expression)},async click(selector){await this.eval(`document.querySelector(${JSON.stringify(selector)}).click()`)}};await p.until(`document.querySelector('#view-online') && document.querySelector('#connection-status').textContent.includes('connected')`);return p}
    const labPage=await page();await labPage.click('[data-view="lab"]');
    const labState=await labPage.eval(`JSON.stringify(state)`);
    assert.equal(await labPage.eval(`document.querySelectorAll('[data-lab-mode]').length`),8);
    await labPage.click('#lab-start');
    async function solveColour(){const square=await labPage.eval(`document.querySelector('#lab-question').textContent.match(/\\b[a-h][1-8]\\b/)[0]`);const answer=((square.charCodeAt(0)-97)+Number(square[1])-1)%2===0?'Dark':'Light';await labPage.eval(`Array.from(document.querySelectorAll('#lab-answers button')).find(b=>b.textContent.endsWith(${JSON.stringify(answer)})).click()`)}
    await labPage.click('#lab-hint');await solveColour();assert.ok((await labPage.eval(`document.querySelector('#lab-counter').textContent`)).includes('0 points'));await labPage.click('#lab-next');
    for(let i=1;i<10;i++){await solveColour();await labPage.click('#lab-next')}
    assert.ok((await labPage.eval(`document.querySelector('#lab-result').textContent`)).includes('9 / 10'));
    assert.equal(await labPage.eval(`JSON.parse(localStorage.getItem('chess-club-lab-results'))[0].score`),9);
    await labPage.click('[data-lab-mode="memory"]');await labPage.click('#lab-start');
    assert.equal(await labPage.eval(`document.querySelector('#lab-answers').hidden`),true);
    await labPage.click('#lab-hide');assert.equal(await labPage.eval(`document.querySelector('#lab-board').hidden`),true);
    await labPage.click('#lab-skip');assert.equal(await labPage.eval(`document.querySelector('#lab-board').hidden`),false);
    await labPage.click('[data-view="play"]');assert.equal(await labPage.eval(`JSON.stringify(state)`),labState);
    for(const mode of ['knight','paths','material','notation','rules','openings']){await labPage.click('[data-view="lab"]');await labPage.click('[data-lab-mode="'+mode+'"]');await labPage.click('#lab-start');assert.equal(await labPage.eval(`document.querySelectorAll('#lab-answers button').length`),4);await labPage.click('#lab-skip');await labPage.click('#lab-end')}
    await labPage.eval(`document.querySelector('#lab-duration').value='60'`);await labPage.click('#lab-start');
    await labPage.eval(`window.labOriginalNow=Date.now;Date.now=()=>window.labOriginalNow()+61000`);
    await labPage.until(`document.querySelector('#lab-result').textContent.startsWith('Time is up')`);
    await labPage.eval(`Date.now=window.labOriginalNow`);
    assert.equal(await labPage.eval(`JSON.parse(localStorage.getItem('chess-club-lab-results')).length`),8,'Empty timed rounds must not create scores');
    await send('Page.reload',{},labPage.sessionId);await labPage.until(`document.querySelector('#lab-history')?.children.length===8`);
    await labPage.click('[data-view="lab"]');await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},labPage.sessionId);
    assert.equal(await labPage.eval(`document.documentElement.scrollWidth<=innerWidth`),true,'Academy lab mobile overflow');
    const labScreenshot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true},labPage.sessionId);fs.writeFileSync(path.join(folder,'academy-lab-mobile.png'),Buffer.from(labScreenshot.data,'base64'));
    const planPage=await page();
    await planPage.click('[data-view="plan"]');assert.equal(await planPage.eval(`document.querySelectorAll('#plan-tasks article').length`),3);
    await planPage.click('[data-plan-kind="lesson"]');
    await planPage.click('#lesson-board [aria-label="e1 White rook"]');await planPage.click('#lesson-board [aria-label="e5 Black pawn"]');
    await planPage.click('#retry-lesson');await planPage.click('#lesson-board [aria-label="e1 White rook"]');await planPage.click('#lesson-board [aria-label="e5 Black pawn"]');
    await planPage.click('[data-view="plan"]');assert.equal(await planPage.eval(`document.querySelector('#plan-progress').value`),1);
    assert.equal(await planPage.eval(`JSON.parse(localStorage.getItem('chess-club-practice-days'))[LearningProgress.dayKey()].lesson.length`),1);
    await planPage.click('[data-plan-kind="opening"]');
    const italian=await planPage.eval(`OPENINGS[0].line`);
    for(let i=0;i<italian.length;i+=2){await planPage.click('#opening-board [aria-label^="'+italian[i].slice(0,2)+' "]');await planPage.click('#opening-board [aria-label^="'+italian[i].slice(2,4)+' "]')}
    assert.equal(await planPage.eval(`JSON.parse(localStorage.getItem('chess-club-opening-schedule'))['italian:white'].streak`),1);
    await planPage.click('[data-view="plan"]');assert.equal(await planPage.eval(`document.querySelector('#plan-progress').value`),2);
    await planPage.click('[data-plan-kind="puzzle"]');
    for(let i=0;i<3;i++){await planPage.until(`trainingSession?.item.generated&&!trainingSession.done`);await planPage.eval(`(()=>{const t=trainingSession,m=core.moveFromUCI(t.state,t.item.line[0]);if(t.selected!==m.from)trainingChoose(m.from);trainingChoose(m.to)})()`);if(i<2)await planPage.click('#next-puzzle')}
    await planPage.click('[data-view="plan"]');assert.equal(await planPage.eval(`document.querySelector('#plan-progress').value`),3);
    await planPage.click('[data-view="profile"]');
    await planPage.eval(`window.realBackupURL=URL.createObjectURL;URL.createObjectURL=blob=>{window.backupText=blob.text();return window.realBackupURL(blob)};localStorage.setItem('chess-club-online','private-session-placeholder')`);
    await planPage.click('#backup-download');
    const backup=await planPage.eval(`window.backupText`);assert.equal(JSON.parse(backup).version,1);assert.ok(!backup.includes('private-session-placeholder'));
    await planPage.eval(`URL.createObjectURL=window.realBackupURL`);
    const importData={format:'advaced-chess-academy-progress',version:1,data:{'chess-club-progress':{puzzles:['back-rank'],lessons:['bishop'],attempts:1,streak:0,lastDay:''},'chess-club-profile':{name:'Restored Explorer',avatar:'♞'}}};
    async function uploadProgress(value){await planPage.eval(`(()=>{const transfer=new DataTransfer();transfer.items.add(new File([${JSON.stringify(JSON.stringify(value))}],'progress.json',{type:'application/json'}));const input=document.querySelector('#backup-file');input.files=transfer.files;input.dispatchEvent(new Event('change'))})()`)}
    await uploadProgress({format:'wrong',version:1,data:{}});await planPage.until(`document.querySelector('#backup-status').textContent.startsWith('Could not load backup:')`);
    await uploadProgress(importData);await planPage.until(`document.querySelector('#backup-preview').hidden===false`);
    assert.equal(await planPage.eval(`progress.lessons.includes('bishop')`),false);
    await planPage.click('#backup-cancel');assert.equal(await planPage.eval(`document.querySelector('#backup-preview').hidden`),true);
    await uploadProgress(importData);await planPage.until(`document.querySelector('#backup-preview').hidden===false`);await planPage.click('#backup-restore');
    await planPage.until(`document.querySelector('#profile-name')?.textContent==='Restored Explorer'`);
    assert.equal(await planPage.eval(`progress.lessons.includes('rook')&&progress.lessons.includes('bishop')`),true);
    assert.equal(await planPage.eval(`progress.puzzles.includes('back-rank')`),true);
    assert.equal(await planPage.eval(`document.querySelector('#view-profile').hidden`),false);
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},planPage.sessionId);
    for(const view of ['profile','plan','openings']){await planPage.click('[data-view="'+view+'"]');assert.equal(await planPage.eval(`document.documentElement.scrollWidth<=window.innerWidth`),true,view+' new tools mobile overflow')}
    const expertPage=await page();
    await expertPage.click('[data-view="puzzles"]');
    assert.deepEqual(await expertPage.eval(`Array.from(document.querySelector('#puzzle-difficulty').options,o=>o.textContent)`),['Easiest (-600)','Easier (-300)','Normal','Harder (+300)','Hardest (+600)']);
    await expertPage.eval(`document.querySelector('#puzzle-difficulty').value='easiest';document.querySelector('#puzzle-difficulty').dispatchEvent(new Event('change'))`);
    await expertPage.until(`trainingSession?.item.difficulty==='easiest'`);
    assert.equal(await expertPage.eval(`document.querySelectorAll('#puzzle-board .selected').length`),1);
    assert.equal(await expertPage.eval(`trainingSession.state.board.filter(Boolean).length<=5`),true);
    const easyPosition=await expertPage.eval(`trainingSession.item.fen`);
    await expertPage.click('#next-puzzle');await expertPage.until(`trainingSession?.item.difficulty==='easiest'&&trainingSession.item.fen!==${JSON.stringify(easyPosition)}`);
    await expertPage.eval(`document.querySelector('#puzzle-difficulty').value='expert';document.querySelector('#puzzle-difficulty').dispatchEvent(new Event('change'))`);
    assert.equal(await expertPage.eval(`document.querySelector('#puzzle-source').value`),'expert');
    assert.equal(await expertPage.eval(`document.querySelector('#puzzle-difficulty').disabled`),false);

    assert.equal(await expertPage.eval(`trainingSession.item.expert`),true);
    await expertPage.eval(`trainingChoose(core.indexOfSquare(trainingSession.item.line[0].slice(0,2)))`);
    assert.equal(await expertPage.eval(`document.querySelectorAll('#puzzle-board .legal').length`),0);
    await expertPage.click('#puzzle-retry');
    for(let i=0;i<3;i++)await expertPage.eval(`(()=>{const t=trainingSession,m=core.allMoves(t.state).find(m=>!t.item.plans[core.square(m.from)+core.square(m.to)]);trainingChoose(m.from);trainingChoose(m.to)})()`);
    assert.equal(await expertPage.eval(`trainingSession.done`),true);
    assert.equal(await expertPage.eval(`expertSolved.length`),0);
    await expertPage.click('#puzzle-reveal');assert.ok((await expertPage.eval(`document.querySelector('#puzzle-feedback').textContent`)).includes('Solution:'));
    async function finishExpert(){
      await expertPage.eval(`(()=>{const t=trainingSession,m=core.moveFromUCI(t.state,Object.keys(t.item.plans)[0]);trainingChoose(m.from);trainingChoose(m.to)})()`);
      await expertPage.until(`trainingSession.step===2&&!trainingSession.busy`);
      await expertPage.eval(`(()=>{const t=trainingSession,m=core.allMoves(t.state).find(m=>{const n=core.apply(t.state,m);return core.check(n,n.turn)&&!core.allMoves(n).length});trainingChoose(m.from);trainingChoose(m.to)})()`);
    }
    await expertPage.click('#puzzle-retry');await expertPage.click('#puzzle-hint');await finishExpert();
    assert.equal(await expertPage.eval(`expertSolved.length`),0);
    await expertPage.click('#puzzle-retry');await finishExpert();
    assert.equal(await expertPage.eval(`expertSolved.length`),1);
    await expertPage.click('#next-puzzle');assert.equal(await expertPage.eval(`trainingSession.state.turn`),'b');await finishExpert();
    assert.equal(await expertPage.eval(`expertSolved.length`),2);
    assert.equal(await expertPage.eval(`JSON.parse(localStorage.getItem('chess-club-expert')).length`),2);
    assert.equal(await expertPage.eval(`progress.puzzles.length`),0);
    assert.equal(await expertPage.eval(`(()=>{const item=TRAINING.expert[0],position=core.fromFEN(item.fen),m=bestMove(position,3);return !!item.plans[core.square(m.from)+core.square(m.to)]})()`),true,'Hard computer finds the quiet mating move');
    await expertPage.eval(`document.querySelector('#puzzle-difficulty').value='easy';document.querySelector('#puzzle-difficulty').dispatchEvent(new Event('change'))`);
    await expertPage.until(`trainingSession?.item.difficulty==='easy'`);
    assert.equal(await expertPage.eval(`document.querySelector('#puzzle-source').value`),'endless');
    await expertPage.eval(`document.querySelector('#puzzle-source').value='expert';document.querySelector('#puzzle-source').dispatchEvent(new Event('change'))`);
    assert.equal(await expertPage.eval(`document.querySelector('#puzzle-difficulty').value`),'expert');
    await expertPage.eval(`document.querySelector('#puzzle-source').value='endless';document.querySelector('#puzzle-source').dispatchEvent(new Event('change'))`);
    await expertPage.until(`trainingSession?.item.difficulty==='easy'`);
    const profilePage=await page();
    await profilePage.click('#profile-shortcut');
    assert.equal(await profilePage.eval(`document.querySelector('#view-profile').hidden`),false);
    assert.equal(await profilePage.eval(`document.querySelectorAll('#profile-stats .stat-card').length`),8);
    await profilePage.eval(`document.querySelector('#profile-nickname').value='David the Knight'`);
    await profilePage.click('#profile-avatars [aria-label="Knight avatar"]');
    await profilePage.click('#profile-form button[type="submit"]');
    assert.equal(await profilePage.eval(`document.querySelector('#profile-name').textContent`),'David the Knight');
    assert.equal(await profilePage.eval(`document.querySelector('#profile-avatar').textContent`),'♞');
    assert.equal(await profilePage.eval(`document.querySelector('#online-name').value`),'David the Knight');
    await send('Page.reload',{},profilePage.sessionId);
    await profilePage.until(`document.querySelector('#profile-name')?.textContent==='David the Knight'`);
    await profilePage.click('[data-view="learn"]');await profilePage.click('[data-lesson="rook"]');
    await profilePage.click('#lesson-board [aria-label="e1 White rook"]');await profilePage.click('#lesson-board [aria-label="e5 Black pawn"]');
    await profilePage.click('[data-view="profile"]');
    assert.equal(await profilePage.eval(`document.querySelectorAll('#profile-stats strong')[1].textContent`),'1 / 16');
    assert.equal(await profilePage.eval(`document.querySelectorAll('#profile-badges .earned').length`),1);
    await profilePage.click('#profile-change-coach');await profilePage.click('[data-coach="bolt"]');await profilePage.click('#profile-shortcut');
    assert.ok((await profilePage.eval(`document.querySelector('#profile-coach').textContent`)).includes('Bolt the Robot'));
    // Render nicknames as text, not markup, and report storage failures honestly.
    await profilePage.eval(`document.querySelector('#profile-nickname').value='<b>Explorer</b>'`);await profilePage.click('#profile-form button[type="submit"]');
    assert.equal(await profilePage.eval(`document.querySelector('#profile-name').textContent`),'<b>Explorer</b>');
    assert.equal(await profilePage.eval(`document.querySelector('#profile-name b')`),null);
    await profilePage.eval(`window.profileOriginalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='chess-club-profile')throw Error('full');return window.profileOriginalSet.call(this,key,value)};document.querySelector('#profile-nickname').value='Unsaved name'`);
    await profilePage.click('#profile-form button[type="submit"]');
    assert.ok((await profilePage.eval(`document.querySelector('#profile-save-status').textContent`)).includes('Could not save'));
    assert.equal(await profilePage.eval(`document.querySelector('#profile-name').textContent`),'<b>Explorer</b>');
    await profilePage.eval(`Storage.prototype.setItem=window.profileOriginalSet`);
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},profilePage.sessionId);
    assert.equal(await profilePage.eval(`document.documentElement.scrollWidth<=window.innerWidth`),true,'Profile mobile overflow');
    const coachPage=await page();
    await coachPage.click('[data-view="coaches"]');
    assert.equal(await coachPage.eval(`document.querySelectorAll('#coach-roster button').length`),8);
    await coachPage.click('[data-coach="luna"]');
    assert.equal(await coachPage.eval(`document.querySelector('#coach-name').textContent`),'Luna the Owl');
    assert.equal(await coachPage.eval(`JSON.parse(localStorage.getItem('chess-club-coach')).id`),'luna');
    const firstTip=await coachPage.eval(`document.querySelector('#coach-advice').textContent`);
    await coachPage.click('#coach-next-tip');assert.notEqual(await coachPage.eval(`document.querySelector('#coach-advice').textContent`),firstTip);
    for(let i=0;i<8;i++){const previous=await coachPage.eval(`document.querySelector('#coach-name').textContent`);await coachPage.click('#coach-random');assert.notEqual(await coachPage.eval(`document.querySelector('#coach-name').textContent`),previous)}
    await coachPage.eval(`document.querySelector('#coach-topic').value='review';document.querySelector('#coach-topic').dispatchEvent(new Event('change'))`);
    assert.ok((await coachPage.eval(`document.querySelector('#coach-advice').textContent`)).includes('mistake'));
    await coachPage.click('[data-coach="zig"]');await coachPage.click('#coach-practise');
    assert.equal(await coachPage.eval(`trainingSession.item.id`),'knight');
    assert.ok((await coachPage.eval(`document.querySelector('#view-learn .coach-companion').textContent`)).includes('Zig the Frog'));
    await coachPage.click('[data-view="coaches"]');await coachPage.click('#coach-random-visits');
    const previousCoach=await coachPage.eval(`document.querySelector('#coach-name').textContent`);
    await coachPage.click('[data-view="learn"]');await coachPage.click('[data-view="coaches"]');
    assert.notEqual(await coachPage.eval(`document.querySelector('#coach-name').textContent`),previousCoach);
    await coachPage.click('#coach-random-visits');await coachPage.click('[data-coach="moss"]');
    await send('Page.reload',{},coachPage.sessionId);
    await coachPage.until(`document.querySelector('#coach-name')?.textContent==='Moss the Turtle'`);
    await coachPage.click('[data-view="coaches"]');await coachPage.click('#coach-practise');
    assert.equal(await coachPage.eval(`document.querySelector('#view-endgames').hidden`),false);
    assert.equal(await coachPage.eval(`past.length`),0);
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},coachPage.sessionId);
    await coachPage.click('[data-view="coaches"]');assert.equal(await coachPage.eval(`document.documentElement.scrollWidth<=window.innerWidth`),true,'Coaches mobile overflow');
    const menuPage=await page();
    await menuPage.eval(`document.querySelector('#academy-nav-search').value='arrows';document.querySelector('#academy-nav-search').dispatchEvent(new Event('input'))`);
    assert.equal(await menuPage.eval(`document.querySelector('.main-nav [data-view="drawing"]').hidden`),false);
    assert.equal(await menuPage.eval(`document.querySelector('.main-nav [data-view="coaches"]').hidden`),true);
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},menuPage.sessionId);
    assert.equal(await menuPage.eval(`getComputedStyle(document.querySelector('#academy-navigation-panel')).display`),'none');
    await menuPage.click('#academy-menu-toggle');
    assert.equal(await menuPage.eval(`document.querySelector('#academy-menu-toggle').getAttribute('aria-expanded')`),'true');
    await menuPage.eval(`document.querySelector('#academy-nav-search').value='coach';document.querySelector('#academy-nav-search').dispatchEvent(new Event('input'))`);
    await menuPage.click('.main-nav [data-view="coaches"]');
    assert.equal(await menuPage.eval(`document.querySelector('#view-coaches').hidden`),false);
    assert.equal(await menuPage.eval(`document.querySelector('#academy-menu-toggle').getAttribute('aria-expanded')`),'false');
    const fullReview=await page();
    const untouched=await fullReview.eval(`JSON.stringify(state)`);
    await fullReview.click('[data-view="review"]');
    await fullReview.eval(`document.querySelector('#review-pgn-input').value='1. f3 e5 2. g4 Qh4# 0-1'`);await fullReview.click('#review-import');
    assert.equal(await fullReview.eval(`document.querySelectorAll('#review-moves button').length`),4);
    await fullReview.eval(`document.querySelector('#review-strength').value='2'`);await fullReview.click('#review-analyse');
    await fullReview.until(`document.querySelector('#review-analysis-status').textContent.startsWith('Complete:')`);
    assert.equal(await fullReview.eval(`document.querySelector('#review-progress').value`),4);
    assert.equal(await fullReview.eval(`document.querySelectorAll('#review-moves button[data-rating="Blunder"]').length`),1);
    assert.equal(await fullReview.eval(`document.querySelectorAll('#review-chart polyline').length`),1);
    assert.notEqual(await fullReview.eval(`document.querySelector('#review-white-accuracy').textContent`),'—');
    await fullReview.click('#review-next-error');assert.equal(await fullReview.eval(`reviewIndex`),3);
    assert.equal(await fullReview.eval(`document.querySelector('#review-rating').textContent`),'Blunder');
    await fullReview.click('#review-best');assert.ok((await fullReview.eval(`document.querySelector('#review-title').textContent`)).startsWith('Suggested:'));
    await fullReview.click('#review-best');assert.equal(await fullReview.eval(`document.querySelector('#review-title').textContent`),'g4');
    await fullReview.eval(`document.querySelector('#review-move-filter').value='errors';document.querySelector('#review-move-filter').dispatchEvent(new Event('change'))`);
    assert.equal(await fullReview.eval(`document.querySelectorAll('#review-moves button:not([hidden])').length`),1);
    await fullReview.eval(`window.originalCreateURL=URL.createObjectURL;URL.createObjectURL=blob=>{window.annotatedText=blob.text();return window.originalCreateURL(blob)}`);
    await fullReview.click('#review-annotated');
    const annotated=await fullReview.eval(`window.annotatedText`);
    assert.ok(annotated.includes('Club estimate: Blunder'));
    assert.equal(await fullReview.eval(`StudyCore.parsePGN(${JSON.stringify(annotated)}).notation.length`),4);
    await fullReview.eval(`URL.createObjectURL=window.originalCreateURL`);
    await fullReview.click('#review-analyse');await fullReview.click('#review-stop');
    assert.equal(await fullReview.eval(`document.querySelector('#review-analyse').disabled`),false);
    const customPGN='[SetUp "1"]\n[FEN "4r1k1/8/8/8/8/8/5PPP/6K1 b - - 0 27"]\n\n27... Re1# 0-1';
    await fullReview.eval(`document.querySelector('#review-pgn-input').value=${JSON.stringify(customPGN)}`);await fullReview.click('#review-import');
    assert.ok((await fullReview.eval(`document.querySelector('#review-moves button').textContent`)).startsWith('27... Re1#'));
    await fullReview.eval(`document.querySelector('#review-pgn-input').value='1. not-a-move'`);await fullReview.click('#review-import');
    assert.ok((await fullReview.eval(`document.querySelector('#review-import-status').textContent`)).includes('Cannot read move'));
    assert.equal(await fullReview.eval(`reviewNotation.length`),1);
    assert.equal(await fullReview.eval(`JSON.stringify(state)`),untouched);
    await fullReview.click('#refresh-review');
    assert.equal(await fullReview.eval(`document.querySelectorAll('#review-moves button').length`),0);
    await fullReview.eval(`document.querySelector('#review-pgn-input').value='1. f3 e5 2. g4 Qh4# 0-1'`);await fullReview.click('#review-import');
    await fullReview.click('#review-analyse');await fullReview.until(`document.querySelector('#review-analysis-status').textContent.startsWith('Complete:')`);
    await fullReview.click('#review-next-error');await fullReview.click('#review-practise-mistake');
    assert.equal(await fullReview.eval(`document.querySelector('#view-clinic').hidden`),false);
    const clinicMove=await fullReview.eval(`JSON.parse(localStorage.getItem('chess-club-mistakes'))[0].solutions[0]`);
    await fullReview.click('#clinic-reveal');assert.equal(await fullReview.eval(`JSON.parse(localStorage.getItem('chess-club-mistakes'))[0].solved`),false);
    await fullReview.click('#clinic-retry');await fullReview.click('#clinic-hint');
    await fullReview.click('#clinic-board [aria-label^="'+clinicMove.slice(0,2)+' "]');await fullReview.click('#clinic-board [aria-label^="'+clinicMove.slice(2,4)+' "]');
    assert.equal(await fullReview.eval(`JSON.parse(localStorage.getItem('chess-club-mistakes'))[0].solved`),false);
    await fullReview.click('#clinic-retry');
    await fullReview.click('#clinic-board [aria-label^="'+clinicMove.slice(0,2)+' "]');await fullReview.click('#clinic-board [aria-label^="'+clinicMove.slice(2,4)+' "]');
    assert.equal(await fullReview.eval(`JSON.parse(localStorage.getItem('chess-club-mistakes'))[0].solved`),true);
    assert.equal(await fullReview.eval(`JSON.stringify(state)`),untouched);
    await send('Page.reload',{},fullReview.sessionId);await fullReview.until(`document.querySelector('#clinic-count')?.textContent.startsWith('1 of 1')`);
    await fullReview.click('[data-view="clinic"]');await fullReview.click('#clinic-remove');
    assert.equal(await fullReview.eval(`JSON.parse(localStorage.getItem('chess-club-mistakes')).length`),0);
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},fullReview.sessionId);
    assert.equal(await fullReview.eval(`document.documentElement.scrollWidth<=window.innerWidth`),true,'Full review mobile overflow');
    const rooms=await page();
    await rooms.click('[data-view="openings"]');
    assert.equal(await rooms.eval(`document.querySelectorAll('#opening-catalog button').length`),8);
    await rooms.eval(`document.querySelector('#opening-search').value='Sicilian';document.querySelector('#opening-search').dispatchEvent(new Event('input'))`);
    assert.equal(await rooms.eval(`document.querySelectorAll('#opening-catalog button').length`),1);
    await rooms.click('[data-opening="sicilian"]');await rooms.click('#opening-favourite');
    assert.equal(await rooms.eval(`JSON.parse(localStorage.getItem('chess-club-opening-favourites'))[0]`),'sicilian');
    await rooms.click('#opening-next');assert.ok((await rooms.eval(`document.querySelector('#opening-status').textContent`)).includes('Move 1'));
    for(const side of ['white','black']){
      await rooms.eval(`document.querySelector('#opening-mode').value='${side}';document.querySelector('#opening-mode').dispatchEvent(new Event('change'))`);
      const line=await rooms.eval(`OPENINGS.find(o=>o.id==='sicilian').line`);
      for(let i=side==='white'?0:1;i<line.length;i+=2){
        await rooms.click('#opening-board [aria-label^="'+line[i].slice(0,2)+' "]');await rooms.click('#opening-board [aria-label^="'+line[i].slice(2,4)+' "]');
      }
      assert.ok((await rooms.eval(`document.querySelector('#opening-status').textContent`)).includes('Line complete'));
    }
    assert.equal(await rooms.eval(`JSON.parse(localStorage.getItem('chess-club-opening-learned')).length`),1);
    await rooms.click('[data-view="endgames"]');
    await rooms.click('#endgame-reveal');assert.equal(await rooms.eval(`localStorage.getItem('chess-club-endgames')`),null);
    for(const id of ['queen-close','ladder','back-rank','black-rank','bishop-finish','promotion']){
      await rooms.click('[data-endgame="'+id+'"]');
      const move=await rooms.eval(`TRAINING.puzzles.find(p=>p.id==='${id}').line[0]`);
      await rooms.click('#endgame-board [aria-label^="'+move.slice(0,2)+' "]');await rooms.click('#endgame-board [aria-label^="'+move.slice(2,4)+' "]');
    }
    assert.equal(await rooms.eval(`JSON.parse(localStorage.getItem('chess-club-endgames')).length`),6);
    await rooms.click('[data-view="rush"]');await rooms.click('#rush-start');
    await rooms.until(`document.querySelectorAll('#rush-board .square').length===64&&!document.querySelector('#rush-skip').disabled`);
    // Derive a solution independently from the displayed board, including Black's orientation.
    const rushMove=await rooms.eval(`(()=>{const s={board:Array(64).fill(null),turn:document.querySelector('#rush-feedback').textContent.startsWith('White')?'w':'b',rights:'',ep:null,half:0};for(const el of document.querySelectorAll('#rush-board .square')){const [square,colour,name]=el.getAttribute('aria-label').split(' ');if(name){const p={king:'k',queen:'q',rook:'r',bishop:'b',knight:'n',pawn:'p'}[name];s.board[ChessCore.indexOfSquare(square)]=colour==='White'?p.toUpperCase():p}}for(let m of ChessCore.allMoves(s)){if(s.board[m.from].toLowerCase()==='p'&&(m.to<8||m.to>=56))m={...m,promotion:'q'};const n=ChessCore.apply(s,m);if(ChessCore.check(n,n.turn)&&!ChessCore.allMoves(n).length)return ChessCore.square(m.from)+ChessCore.square(m.to)}throw Error('No rush mate')})()`);
    await rooms.click('#rush-board [aria-label^="'+rushMove.slice(0,2)+' "]');await rooms.click('#rush-board [aria-label^="'+rushMove.slice(2,4)+' "]');
    assert.equal(await rooms.eval(`document.querySelector('#rush-score').textContent`),'1');
    await rooms.click('#rush-next');
    for(let i=0;i<3;i++){await rooms.until(`!document.querySelector('#rush-skip').disabled`);await rooms.click('#rush-skip')}
    assert.equal(await rooms.eval(`document.querySelector('#rush-start').disabled`),false);
    assert.equal(await rooms.eval(`JSON.parse(localStorage.getItem('chess-club-rush-runs'))[0].score`),1);
    await rooms.click('#rush-start');await rooms.click('[data-view="glossary"]');
    assert.equal(await rooms.eval(`document.querySelector('#rush-start').disabled`),false);
    await rooms.click('[data-view="rush"]');await rooms.click('#rush-start');
    await rooms.eval(`window.realNow=Date.now;Date.now=()=>window.realNow()+600000`);
    await rooms.until(`document.querySelector('#rush-start').disabled===false`);
    await rooms.eval(`Date.now=window.realNow`);
    assert.ok((await rooms.eval(`document.querySelector('#rush-feedback').textContent`)).includes('Time is up'));
    assert.equal(await rooms.eval(`past.length`),0);
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},rooms.sessionId);
    for(const key of ['openings','endgames','rush']){await rooms.click('[data-view="'+key+'"]');assert.equal(await rooms.eval(`document.documentElement.scrollWidth<=window.innerWidth`),true,key+' mobile overflow')}
    const guided=await page();
    await guided.click('[data-view="learn"]');
    assert.equal(await guided.eval(`document.querySelectorAll('#lesson-grid .lesson-card').length`),16);
    for(const [level,count] of [['easy',7],['medium',6],['hard',3]]){
      await guided.eval(`document.querySelector('#guided-difficulty').value='${level}';document.querySelector('#guided-difficulty').dispatchEvent(new Event('change'))`);
      assert.equal(await guided.eval(`document.querySelectorAll('#lesson-grid .lesson-card').length`),count);
    }
    await guided.click('[data-lesson="knight-fork"]');
    await guided.eval(`(()=>{const m=core.moveFromUCI(trainingSession.state,trainingSession.item.moves[0]);trainingChoose(m.from);trainingChoose(m.to)})()`);
    assert.equal(await guided.eval(`trainingSession.done`),false);
    assert.equal(await guided.eval(`progress.lessons.length`),0);
    await guided.until(`trainingSession.step===2&&!trainingSession.busy`);
    await guided.click('#lesson-hint');
    assert.ok((await guided.eval(`document.querySelector('#lesson-feedback').textContent`)).includes('d8'));
    await guided.eval(`(()=>{const m=core.moveFromUCI(trainingSession.state,trainingSession.item.moves[2]);trainingChoose(m.from);trainingChoose(m.to)})()`);
    assert.equal(await guided.eval(`trainingSession.done`),true);
    assert.equal(await guided.eval(`progress.lessons.includes('knight-fork')`),true);
    await guided.click('#next-lesson');
    assert.equal(await guided.eval(`trainingSession.item.id`),'rook-skewer');
    await guided.click('#lesson-reveal');
    assert.equal(await guided.eval(`progress.lessons.includes('rook-skewer')`),false);
    assert.ok((await guided.eval(`document.querySelector('#lesson-feedback').textContent`)).includes('Rxa8'));
    await guided.click('#retry-lesson');
    for(const id of ['rook-skewer','discovered-check']){
      assert.equal(await guided.eval(`trainingSession.item.id`),id);
      await guided.eval(`(()=>{const m=core.moveFromUCI(trainingSession.state,trainingSession.item.moves[0]);trainingChoose(m.from);trainingChoose(m.to)})()`);
      await guided.until(`trainingSession.step===2&&!trainingSession.busy`);
      await guided.eval(`(()=>{const m=core.moveFromUCI(trainingSession.state,trainingSession.item.moves[2]);trainingChoose(m.from);trainingChoose(m.to)})()`);
      assert.equal(await guided.eval(`trainingSession.done`),true);
      await guided.click('#next-lesson');
    }
    assert.equal(await guided.eval(`document.querySelector('#lesson-catalog').hidden`),false);
    assert.equal(await guided.eval(`document.querySelectorAll('#lesson-grid .lesson-card').length`),3);
    assert.ok((await guided.eval(`document.querySelector('#learn-progress').textContent`)).includes('3 of 16'));
    const a=await page();
    assert.equal(await a.eval(`document.querySelectorAll('#board .square').length`),64);
    await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false},a.sessionId);
    await a.click('[data-view="puzzles"]');
    await a.until(`trainingSession?.item.generated===true`);
    assert.equal(await a.eval(`trainingSession.item.difficulty`),'easy');
    const firstEndless=await a.eval(`trainingSession.item.fen`);
    await a.click('#next-puzzle');await a.until(`trainingSession?.item.generated&&trainingSession.item.fen!==${JSON.stringify(firstEndless)}`);
    for(const level of ['medium','hard']){
      await a.eval(`document.querySelector('#puzzle-difficulty').value='${level}';document.querySelector('#puzzle-difficulty').dispatchEvent(new Event('change'))`);
      await a.until(`trainingSession?.item.difficulty==='${level}'`);
    }
    const hardPosition=await a.eval(`trainingSession.item.fen`);
    await a.click('#puzzle-hint');
    assert.ok((await a.eval(`document.querySelector('#puzzle-feedback').textContent`)).includes('Look for a check'));
    await a.click('#puzzle-reveal');
    assert.equal(await a.eval(`endlessSolved`),0);
    await a.click('#puzzle-retry');
    assert.equal(await a.eval(`trainingSession.item.fen`),hardPosition);
    await a.eval(`(()=>{const m=core.moveFromUCI(trainingSession.state,trainingSession.item.line[0]);trainingChoose(m.from);trainingChoose(m.to)})()`);
    assert.equal(await a.eval(`trainingSession.done`),true);
    assert.equal(await a.eval(`endlessSolved`),1);
    assert.equal(await a.eval(`progress.puzzles.length`),0);
    assert.equal(await a.eval(`JSON.parse(localStorage.getItem('chess-club-endless')).solved`),1);
    await a.click('#puzzle-retry');
    await a.eval(`(()=>{const m=core.moveFromUCI(trainingSession.state,trainingSession.item.line[0]);trainingChoose(m.from);trainingChoose(m.to)})()`);
    assert.equal(await a.eval(`endlessSolved`),1);
    // A collection change cancels a generated request instead of replacing the chosen lesson.
    await a.click('#next-puzzle');await a.eval(`startPuzzle(0)`);
    await delay(100);
    assert.equal(await a.eval(`trainingSession.item.id`),'back-rank');
    assert.equal(await a.eval(`document.querySelector('#puzzle-source').value`),'library');
    await a.click('[data-view="learn"]');
    await a.click('#start-endless-lessons');
    await a.until(`trainingSession?.kind==='lesson'&&trainingSession.item.generated`);
    assert.equal(await a.eval(`trainingSession.item.difficulty`),'easy');
    const initialLesson=await a.eval(`trainingSession.item.fen`);
    await a.click('#next-lesson');await a.until(`trainingSession?.kind==='lesson'&&trainingSession.item.fen!==${JSON.stringify(initialLesson)}`);
    await a.eval(`document.querySelector('#lesson-difficulty').value='medium';document.querySelector('#lesson-difficulty').dispatchEvent(new Event('change'))`);
    await a.until(`trainingSession?.item.difficulty==='medium'`);
    await a.eval(`document.querySelector('#lesson-difficulty').value='hard';document.querySelector('#lesson-difficulty').dispatchEvent(new Event('change'));document.querySelector('#lesson-topic').value='n';document.querySelector('#lesson-topic').dispatchEvent(new Event('change'))`);
    await a.until(`trainingSession?.item.difficulty==='hard'&&trainingSession.item.topic==='n'`);
    await a.click('#lesson-hint');assert.ok((await a.eval(`document.querySelector('#lesson-feedback').textContent`)).includes('Start on'));
    await a.click('#lesson-reveal');assert.equal(await a.eval(`endlessLessonsSolved`),0);
    await a.click('#retry-lesson');
    await a.eval(`(()=>{const m=core.moveFromUCI(trainingSession.state,trainingSession.item.moves[0]);trainingChoose(m.from);trainingChoose(m.to)})()`);
    assert.equal(await a.eval(`endlessLessonsSolved`),1);assert.equal(await a.eval(`progress.lessons.length`),0);assert.equal(await a.eval(`endlessSolved`),1);
    assert.equal(await a.eval(`JSON.parse(localStorage.getItem('chess-club-endless-lessons')).solved`),1);
    await a.click('#retry-lesson');await a.eval(`(()=>{const m=core.moveFromUCI(trainingSession.state,trainingSession.item.moves[0]);trainingChoose(m.from);trainingChoose(m.to)})()`);
    assert.equal(await a.eval(`endlessLessonsSolved`),1);
    await a.click('#next-lesson');await a.click('#back-lessons');await delay(100);
    assert.equal(await a.eval(`document.querySelector('#lesson-catalog').hidden`),false);
    assert.equal(await a.eval(`document.querySelector('#lesson-study').hidden`),true);
    assert.equal(await a.eval(`document.querySelector('#lesson-source').value`),'library');
    await a.click('[data-view="glossary"]');
    assert.equal(await a.eval(`document.querySelector('#view-glossary').hidden`),false);
    assert.equal(await a.eval(`document.querySelector('#club-page-label').textContent`),'Chess glossary');
    assert.equal(await a.eval(`document.querySelectorAll('#glossary-grid article').length`),24);
    await a.eval(`document.querySelector('#glossary-search').value='stalemate';document.querySelector('#glossary-search').dispatchEvent(new Event('input'))`);
    assert.equal(await a.eval(`document.querySelectorAll('#glossary-grid article').length`),1);
    await a.eval(`document.querySelector('#glossary-topic').value='Tactics';document.querySelector('#glossary-topic').dispatchEvent(new Event('change'))`);
    assert.equal(await a.eval(`document.querySelectorAll('#glossary-grid article').length`),0);
    assert.ok((await a.eval(`document.querySelector('#glossary-count').textContent`)).includes('No matching words'));
    await a.eval(`document.querySelector('#glossary-search').value='';document.querySelector('#glossary-search').dispatchEvent(new Event('input'))`);
    assert.equal(await a.eval(`document.querySelectorAll('#glossary-grid article').length`),6);
    await a.click('[data-view="mates"]');
    assert.equal(await a.eval(`document.querySelectorAll('#mate-patterns article').length`),6);
    for(const id of ['back-rank','queen-close','ladder','smothered','bishop-finish','black-queen']){
      await a.click('[data-view="mates"]');
      await a.click('[data-pattern="'+id+'"]');
      assert.equal(await a.eval(`TRAINING.puzzles[puzzleIndex].id`),id);
      assert.equal(await a.eval(`document.querySelector('#view-puzzles').hidden`),false);
      assert.equal(await a.eval(`puzzleFilter`),'Checkmate');
    }
    assert.equal(await a.eval(`past.length`),0);
    await a.click('[data-view="tournaments"]');
    await a.click('#drawing-tools-nav');
    assert.equal(await a.eval(`document.querySelector('#view-play').hidden`),false);
    assert.equal(await a.eval(`document.querySelector('#drawing-tools-panel').hidden`),false);
    assert.equal(await a.eval(`document.querySelector('#arrow-mode').closest('header')!==null`),true);
    assert.equal(await a.eval(`document.querySelector('#arrow-mode').getAttribute('aria-pressed')`),'true');
    await a.click('#drawing-tools-panel > button');
    assert.equal(await a.eval(`document.querySelector('#drawing-tools-nav').getAttribute('aria-expanded')`),'false');
    // Real right-button drag creates an annotation without moving a piece.
    async function squarePoint(label){return a.eval(`(()=>{const r=document.querySelector('#board [aria-label^="${label} "]').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`)}
    await a.eval(`document.querySelector('#board').scrollIntoView({block:'center'})`);
    const from=await squarePoint('e2'),to=await squarePoint('e4');
    await send('Input.dispatchMouseEvent',{type:'mousePressed',...from,button:'right',buttons:2,clickCount:1},a.sessionId);
    await send('Input.dispatchMouseEvent',{type:'mouseMoved',...to,button:'right',buttons:2},a.sessionId);
    await send('Input.dispatchMouseEvent',{type:'mouseReleased',...to,button:'right',buttons:0,clickCount:1},a.sessionId);
    assert.equal(await a.eval(`document.querySelectorAll('.board-arrows path[data-from="e2"][data-to="e4"]').length`),1);
    assert.equal(await a.eval(`past.length`),0);
    const beforeFlip=await a.eval(`document.querySelector('.board-arrows path').getAttribute('transform')`);
    await a.click('#flip');
    assert.notEqual(await a.eval(`document.querySelector('.board-arrows path').getAttribute('transform')`),beforeFlip);
    await a.click('#flip');
    await a.click('#arrow-mode');
    await a.click('#board [aria-label^="e2 "]');await a.click('#board [aria-label^="e4 "]');
    assert.equal(await a.eval(`document.querySelectorAll('.board-arrows path').length`),0);
    // Laptop trackpads emit primary-button events; both drag and two clicks work.
    await send('Input.dispatchMouseEvent',{type:'mousePressed',...from,button:'left',buttons:1,clickCount:1},a.sessionId);
    await send('Input.dispatchMouseEvent',{type:'mouseMoved',...to,button:'left',buttons:1},a.sessionId);
    await send('Input.dispatchMouseEvent',{type:'mouseReleased',...to,button:'left',buttons:0,clickCount:1},a.sessionId);
    assert.equal(await a.eval(`document.querySelectorAll('.board-arrows path').length`),1);
    for(const point of [from,to]){
      await send('Input.dispatchMouseEvent',{type:'mousePressed',...point,button:'left',buttons:1,clickCount:1},a.sessionId);
      await send('Input.dispatchMouseEvent',{type:'mouseReleased',...point,button:'left',buttons:0,clickCount:1},a.sessionId);
    }
    assert.equal(await a.eval(`document.querySelectorAll('.board-arrows path').length`),0);
    assert.equal(await a.eval(`past.length`),0);
    for(const expected of ['false','true']){
      await send('Input.dispatchKeyEvent',{type:'keyDown',key:'a',code:'KeyA',windowsVirtualKeyCode:65},a.sessionId);
      await send('Input.dispatchKeyEvent',{type:'keyUp',key:'a',code:'KeyA',windowsVirtualKeyCode:65},a.sessionId);
      assert.equal(await a.eval(`document.querySelector('#arrow-mode').getAttribute('aria-pressed')`),expected);
    }
    // Coloured square circles, recolouring, and drawing undo stay separate from chess moves.
    await a.eval(`document.querySelector('#drawing-shape').value='circle';document.querySelector('#drawing-shape').dispatchEvent(new Event('change'));document.querySelector('#drawing-colour').value='#e75050'`);
    await a.click('#board [aria-label^="d4 "]');
    assert.equal(await a.eval(`document.querySelectorAll('.board-arrows circle[data-square="d4"]').length`),1);
    assert.equal(await a.eval(`document.querySelector('.board-arrows circle[data-square]').style.stroke`),'rgb(231, 80, 80)');
    const circleBefore=await a.eval(`document.querySelector('.board-arrows circle[data-square]').getAttribute('cx')`);
    await a.click('#flip');
    assert.notEqual(await a.eval(`document.querySelector('.board-arrows circle[data-square]').getAttribute('cx')`),circleBefore);
    await a.click('#flip');
    await a.eval(`document.querySelector('#drawing-colour').value='#489aef'`);
    await a.click('#board [aria-label^="d4 "]');
    assert.equal(await a.eval(`document.querySelectorAll('.board-arrows circle[data-square]').length`),1);
    assert.equal(await a.eval(`document.querySelector('.board-arrows circle[data-square]').style.stroke`),'rgb(72, 154, 239)');
    await a.click('#undo-drawing');
    assert.equal(await a.eval(`document.querySelector('.board-arrows circle[data-square]').style.stroke`),'rgb(231, 80, 80)');
    await a.click('#clear-arrows');await a.click('#undo-drawing');
    assert.equal(await a.eval(`document.querySelectorAll('.board-arrows circle[data-square]').length`),1);
    await a.click('#clear-arrows');
    await a.eval(`document.querySelector('#drawing-shape').value='arrow';document.querySelector('#drawing-shape').dispatchEvent(new Event('change'))`);
    await a.click('#board [aria-label^="e2 "]');await a.click('#board [aria-label^="e4 "]');
    assert.equal(await a.eval(`document.querySelector('.board-arrows path').dataset.colour`),'#489aef');
    await a.click('#undo-drawing');
    assert.equal(await a.eval(`document.querySelectorAll('.board-arrows path').length`),0);
    assert.equal(await a.eval(`past.length`),0);
    await a.eval(`document.querySelector('#drawing-colour').value='#ef9c20'`);
    // Touch taps support choosing the two ends while Arrow mode is enabled.
    for(const point of [from,to]){
      await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...point,radiusX:2,radiusY:2}]},a.sessionId);
      await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]},a.sessionId);
    }
    assert.equal(await a.eval(`document.querySelectorAll('.board-arrows path').length`),1);
    assert.equal(await a.eval(`past.length`),0);
    await a.click('#clear-arrows');
    assert.equal(await a.eval(`document.querySelectorAll('.board-arrows path').length`),0);
    await a.click('#board [aria-label^="e2 "]');await a.click('#board [aria-label^="e4 "]');
    await a.click('#arrow-mode');
    await a.click('#board [aria-label^="e2 "]');await a.click('#board [aria-label^="e4 "]');
    assert.equal(await a.eval(`past.length`),1);
    assert.equal(await a.eval(`document.querySelectorAll('.board-arrows path').length`),0);
    await a.click('#undo');
    assert.equal(await a.eval(`document.body.classList.contains('club-shell')`),true);
    assert.equal(await a.eval(`document.querySelector('.brand-mark').textContent`),'♛');
    assert.ok((await a.eval(`document.title`)).includes('Advaced Chess Academy'));
    assert.equal(await a.eval(`fetch(document.querySelector('link[rel=icon]').href).then(r=>r.status)`),200);
    assert.equal(await a.eval(`document.querySelectorAll('.achievement-card.earned').length`),0);
    await delay(300);
    const homeShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true},a.sessionId);
    fs.writeFileSync(path.join(folder,'club-home.png'),Buffer.from(homeShot.data,'base64'));
    await a.click('#appearance-toggle');
    assert.equal(await a.eval(`document.documentElement.dataset.appearance`),'night');
    await a.click('#board-focus');
    assert.equal(await a.eval(`getComputedStyle(document.querySelector('#view-play .intro')).display`),'none');
    await delay(300);
    const focusShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true},a.sessionId);
    fs.writeFileSync(path.join(folder,'club-night-focus.png'),Buffer.from(focusShot.data,'base64'));
    await a.click('#board-focus');
    await a.click('#appearance-toggle');
    await a.click('.mission-button');
    assert.equal(await a.eval(`document.querySelector('#view-puzzles').hidden`),false);
    assert.equal(await a.eval(`document.querySelector('#club-page-label').textContent`),'Puzzles');
    await a.eval(`startPuzzle(0)`);

    await a.click('[data-view="puzzles"]');
    await a.click('#puzzle-board [aria-label="e1 White rook"]');
    await a.click('#puzzle-board [aria-label="e8 empty"]');
    assert.ok((await a.eval(`document.querySelector('#puzzle-feedback').textContent`)).includes('Re8#'));
    assert.equal(await a.eval(`progress.puzzles.length`),1);
    await a.eval(`startPuzzle(11)`);
    await a.click('#puzzle-board [aria-label="e5 White knight"]');
    await a.click('#puzzle-board [aria-label="f7 empty"]');
    await a.until(`trainingSession.step===2`);
    await a.click('#puzzle-board [aria-label="f7 White knight"]');
    await a.click('#puzzle-board [aria-label="d8 Black queen"]');
    assert.equal(await a.eval(`trainingSession.done`),true);
    await a.click('[data-view="learn"]');
    await a.click('#lesson-grid .lesson-card');
    await a.click('#lesson-board [aria-label="e1 White rook"]');
    await a.click('#lesson-board [aria-label="e5 Black pawn"]');
    assert.equal(await a.eval(`progress.lessons.length`),1);
    assert.equal(await a.eval(`document.querySelectorAll('.achievement-card.earned').length`),2);
    await a.click('#achievement-lessons');
    assert.equal(await a.eval(`document.querySelector('#view-learn').hidden`),false);
    await a.click('[data-view="play"]');
    await a.click('#board [aria-label="e2 White pawn"]');
    await a.click('#board [aria-label^="e4 empty"]');
    await a.click('[data-view="review"]');
    assert.equal(await a.eval(`document.querySelector('#review-title').textContent`),'e4');
    await a.click('#review-first');
    assert.equal(await a.eval(`reviewIndex`),0);
    assert.equal(await a.eval(`state.board[36]`),'P');
    await a.click('[data-view="online"]');
    await a.eval(`document.querySelector('#online-name').value='Alice'`);
    await a.click('#create-room');
    await a.until(`online!==null`);
    const room=await a.eval(`online.id`);
    assert.equal(await a.eval(`document.querySelector('#hint').disabled`),true);
    const study=await page();
    await study.click('a[href="chess-extras/index.html"]');
    await study.until(`document.querySelectorAll('#analysis-board .square').length===64`);
    assert.equal(await study.eval(`document.querySelector('[data-area="drawing"]').getAttribute('href')`),'../david.html#drawing');
    await study.click('#analysis-board [aria-label="e2 White pawn"]');
    await study.click('#analysis-board [aria-label="e4 empty"]');
    assert.equal(await study.eval(`document.querySelector('#position-count').textContent`),'Ply 1 of 1');
    await study.eval(`document.querySelector('#study-notes').value='Control the center';document.querySelector('#study-notes').dispatchEvent(new Event('input'))`);
    await study.click('#save-study');
    await study.eval(`document.querySelector('#save-title').value='My opening idea'`);
    await study.click('#confirm-save');
    await study.click('[data-tab="library"]');
    assert.equal(await study.eval(`document.querySelector('#library-grid h3').textContent`),'My opening idea');
    await study.click('#library-grid .primary');
    assert.equal(await study.eval(`document.querySelector('#study-notes').value`),'Control the center');
    await study.click('#open-import');
    await study.eval(`document.querySelector('#pgn-input').value='1. e4 e5 2. Nf3 Nc6 *'`);
    await study.click('#import-pgn');
    assert.equal(await study.eval(`document.querySelector('#position-count').textContent`),'Ply 4 of 4');
    await study.eval(`document.querySelector('#fen').value='6k1/5ppp/8/8/8/8/8/4R1K1 w - - 0 1'`);
    await study.click('#load-fen');
    await study.click('#suggest');
    await study.until(`document.querySelector('#candidates button')`);
    assert.equal(await study.eval(`document.querySelector('#candidates strong').textContent`),'Re8#');
    await study.click('[data-tab="openings"]');
    await study.click('#opening-catalog .opening-card');
    for (const [n,from,to] of [[0,'e2','e4'],[2,'g1','f3'],[4,'f1','c4'],[6,'c2','c3']]) {
      await study.click('#opening-board [aria-label^="'+from+' "]');
      await study.click('#opening-board [aria-label^="'+to+' "]');
      await study.until(`document.querySelector('#trainer-progress').textContent==='${n+2} / 8 plies'`);
    }
    assert.equal(await study.eval(`document.querySelector('#trainer-turn').textContent`),'Line complete');
    await study.eval(`document.querySelector('#practice-side').value='b';document.querySelector('#practice-side').dispatchEvent(new Event('change'))`);
    await study.until(`document.querySelector('#trainer-progress').textContent==='1 / 8 plies'`);
    for(const [n,from,to] of [[1,'e7','e5'],[3,'b8','c6'],[5,'f8','c5'],[7,'g8','f6']]) {
      await study.click('#opening-board [aria-label^="'+from+' "]');
      await study.click('#opening-board [aria-label^="'+to+' "]');
      await study.until(`document.querySelector('#trainer-progress').textContent==='${Math.min(n+2,8)} / 8 plies'`);
    }
    assert.equal(await study.eval(`JSON.parse(localStorage.getItem('chess-club-openings-v1')).length`),2);
    await study.click('#study-opening');
    assert.equal(await study.eval(`document.querySelector('#position-count').textContent`),'Ply 8 of 8');
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},study.sessionId);
    assert.equal(await study.eval(`document.documentElement.scrollWidth<=window.innerWidth`),true,'Study mobile overflow');
    const studyShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true},study.sessionId);
    fs.writeFileSync(path.join(folder,'study-mobile.png'),Buffer.from(studyShot.data,'base64'));
    await study.click('[data-tab="library"]');
    await study.click('#library-grid .danger');
    await study.click('#confirm-delete');
    assert.equal(await study.eval(`JSON.parse(localStorage.getItem('chess-club-studies-v1')).length`),0);
    const watch=await page();
    await send('Emulation.setDeviceMetricsOverride',{width:1360,height:1000,deviceScaleFactor:1,mobile:false},watch.sessionId);
    await watch.click('a[href="chess-extras/watch.html"]');
    await watch.until(`document.querySelector('#player-status').textContent.includes('Lichess')`);
    await watch.click('#favorite-source');
    await watch.click('[data-filter="saved"]');
    assert.equal(await watch.eval(`document.querySelectorAll('.channel-button').length`),1);
    await watch.click('[data-filter="all"]');
    await watch.click('.channel-button:nth-child(2)');
    assert.equal(await watch.eval(`new URL(document.querySelector('#player iframe').src).searchParams.get('parent')`),'127.0.0.1');
    await watch.eval(`document.querySelector('#stream-url').value='https://www.youtube.com/watch?v=abcdefghijk';document.querySelector('#custom-stream').requestSubmit()`);
    assert.equal(await watch.eval(`new URL(document.querySelector('#player iframe').src).hostname`),'www.youtube-nocookie.com');
    await watch.eval(`document.querySelector('#stream-url').value='https://youtube.com.evil.example/watch?v=abcdefghijk';document.querySelector('#custom-stream').requestSubmit()`);
    assert.ok((await watch.eval(`document.querySelector('#stream-error').textContent`)).length>0);
    await watch.click('#focus-mode');
    assert.equal(await watch.eval(`document.querySelector('#focus-mode').getAttribute('aria-pressed')`),'true');
    await watch.click('#focus-mode');
    await watch.click('.channel-button:first-child');
    await delay(6000);
    const watchShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true},watch.sessionId);
    fs.writeFileSync(path.join(folder,'watch-desktop.png'),Buffer.from(watchShot.data,'base64'));
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},watch.sessionId);
    await watch.click('.channel-button:nth-child(2)');
    assert.equal(await watch.eval(`document.querySelector('#player iframe')`),null,'Small screens should use Twitch direct-link fallback');
    assert.equal(await watch.eval(`document.documentElement.scrollWidth<=window.innerWidth`),true,'Watch mobile overflow');
    const clubA=await page();
    await clubA.click('a[href="chess-extras/community.html"]');
    await clubA.until(`document.querySelector('#feed-count').textContent==='0 conversations'`);
    await clubA.click('#new-post');
    await clubA.eval(`document.querySelector('#nickname').value='KnightExplorer'`);
    await clubA.click('#save-profile');
    await clubA.until(`document.querySelector('#compose-dialog').open`);
    await clubA.eval(`document.querySelector('#post-title').value='When should I castle?';document.querySelector('#post-text').value='How can I keep my king safe? <img src=x onerror=alert(1)>'`);
    await clubA.click('#publish-post');
    await clubA.until(`document.querySelector('#thread-dialog').open`);
    assert.equal(await clubA.eval(`document.querySelector('#thread-text img')`),null);
    await clubA.click('[data-close="thread-dialog"]');
    const clubB=await page();
    await clubB.click('a[href="chess-extras/community.html"]');
    await clubB.until(`document.querySelector('.post-title')`);
    await clubB.click('.post-title');
    await clubB.until(`document.querySelector('#thread-dialog').open`);
    assert.equal(await clubB.eval(`document.querySelector('#thread-title').textContent`),'When should I castle?');
    await clubB.click('#thread-actions button:first-child');
    await clubB.eval(`document.querySelector('#nickname').value='BishopBuddy'`);
    await clubB.click('#save-profile');
    await clubB.until(`document.querySelector('#thread-actions button').getAttribute('aria-pressed')==='true'`);
    await clubB.eval(`document.querySelector('#reply-text').value='Try developing your pieces and checking that the castling path is safe.'`);
    await clubB.click('#send-reply');
    await clubB.until(`document.querySelectorAll('#replies .reply').length===1`);
    await clubA.click('#refresh-posts');
    await clubA.until(`document.querySelector('.post-footer').textContent.includes('1 reply')`);
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},clubA.sessionId);
    assert.equal(await clubA.eval(`document.documentElement.scrollWidth<=window.innerWidth`),true,'Community mobile overflow');
    const communityShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true},clubA.sessionId);
    fs.writeFileSync(path.join(folder,'community-mobile.png'),Buffer.from(communityShot.data,'base64'));
    await clubB.click('#thread-actions button:nth-child(3)');
    await clubB.click('#submit-report');
    await clubB.until(`!document.querySelector('#report-dialog').open`);
    await clubA.click('#refresh-posts');
    await clubA.until(`document.querySelectorAll('.post-card').length===0`);
    await clubA.click('#open-moderation');
    const moderatorKey=fs.readFileSync(path.join(folder,'data','community-moderator-key'),'utf8').trim();
    await clubA.eval(`document.querySelector('#moderator-key').value=${JSON.stringify(moderatorKey)};document.querySelector('#moderator-form').requestSubmit()`);
    await clubA.until(`document.querySelector('.moderation-card')`);
    await clubA.click('.moderation-card .button-row button:first-child');
    await clubA.until(`document.querySelector('#moderation-posts').textContent.includes('No reported')`);
    await clubA.click('[data-close="moderation-dialog"]');
    await clubA.until(`document.querySelector('.post-title')`);
    await clubA.click('.post-title');
    await clubA.until(`document.querySelector('#thread-dialog').open`);
    await clubA.click('#thread-actions button:last-child');
    await clubA.click('#confirm-delete');
    await clubA.until(`document.querySelectorAll('.post-card').length===0`);
    const b=await page();
    await b.click('[data-view="online"]');
    await b.eval(`document.querySelector('#online-name').value='Bob';document.querySelector('#room-code').value=${JSON.stringify(room)}`);
    await b.click('#join-room');
    await b.until(`online!==null`);
    await a.until(`online.snapshot.waiting===false`);
    await a.eval(`document.querySelector('#board [aria-label=\"e2 White pawn\"]').focus()`);
    await delay(1200);
    assert.equal(await a.eval(`document.activeElement.getAttribute('aria-label')`),'e2 White pawn','Polling must preserve keyboard focus');
    await a.click('#board [aria-label="e2 White pawn"]');
    await a.click('#board [aria-label^="e4 empty"]');
    await b.until(`state.board[36]==='P'`);
    await b.click('#board [aria-label="e7 Black pawn"]');
    await b.click('#board [aria-label^="e5 empty"]');
    await a.until(`state.board[28]==='p'`);
    await b.eval(`document.querySelector('#chat-input').value='<img src=x onerror=alert(1)>';document.querySelector('#chat-form').requestSubmit()`);
    await a.until(`document.querySelector('#chat-list').textContent.includes('<img')`);
    assert.equal(await a.eval(`document.querySelector('#chat-list img')`),null);
    await a.click('#offer-draw');
    await b.until(`online.snapshot.drawOffer==='w'`);
    await b.click('#offer-draw');
    await a.until(`finished?.title==='Draw by agreement'`);
    await a.click('#leave-online'); await a.click('#confirm-leave');
    assert.equal(await a.eval(`online`),null);
    assert.equal(await a.eval(`notation.join(' ')`),'e4');
    await a.click('#reconnect-area button');
    await a.until(`online!==null`);
    assert.equal(await a.eval(`finished.title`),'Draw by agreement');
    await send('Emulation.setDeviceMetricsOverride',{width:1360,height:1100,deviceScaleFactor:1,mobile:false},a.sessionId);
    const desktop=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true},a.sessionId);
    fs.writeFileSync(path.join(folder,'desktop.png'),Buffer.from(desktop.data,'base64'));
    await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},a.sessionId);
    await a.click('[data-view="puzzles"]');
    assert.equal(await a.eval(`document.documentElement.scrollWidth<=window.innerWidth`),true,'Mobile horizontal overflow');
    const mobile=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true},a.sessionId);
    fs.writeFileSync(path.join(folder,'mobile.png'),Buffer.from(mobile.data,'base64'));
    await a.click('[data-view="history"]');
    assert.ok(await a.eval(`document.querySelectorAll('.saved-game').length>=2`));
    await a.click('.saved-game .primary');
    assert.equal(await a.eval(`reviewIndex`),0);
    await a.click('[data-view="train"]');
    await a.click('#coordinate-start');
    const target=await a.eval(`document.querySelector('#coordinate-status').textContent.match(/Find ([a-h][1-8])/)[1]`);
    await a.click('#coordinate-board [data-square="'+target+'"]');
    assert.ok((await a.eval(`document.querySelector('#coordinate-status').textContent`)).includes('1 correct'));
    assert.equal(await a.eval(`document.documentElement.scrollWidth<=window.innerWidth`),true,'Training mobile overflow');
    const hostPage=await page(),friendPage=await page();
    await hostPage.click('[data-view="tournaments"]');
    await hostPage.eval(`document.querySelector('#tournament-create [name=name]').value='Cup host';document.querySelector('#tournament-create').requestSubmit()`);
    await hostPage.until(`document.querySelector('#tournament-start')`);
    const cupCode=await hostPage.eval(`document.querySelector('[aria-label="Tournament invite code"]').value`);
    await friendPage.click('[data-view="tournaments"]');
    await friendPage.eval(`document.querySelector('#tournament-join [name=name]').value='Cup friend';document.querySelector('#tournament-join [name=code]').value='${cupCode}';document.querySelector('#tournament-join').requestSubmit()`);
    await friendPage.until(`document.querySelector('#tournament-refresh')`);
    await hostPage.click('#tournament-start');
    await hostPage.until(`document.querySelector('.tournament-match button')`);
    await friendPage.click('#tournament-refresh');
    await friendPage.until(`document.querySelector('.tournament-match button')`);
    await hostPage.click('.tournament-match button');
    await friendPage.click('.tournament-match button');
    await hostPage.until(`online!==null`);await friendPage.until(`online!==null`);
    assert.equal(await hostPage.eval(`online.id`),await friendPage.eval(`online.id`));
    await hostPage.click('#board [aria-label="e2 White pawn"]');await hostPage.click('#board [aria-label^="e4 empty"]');
    await friendPage.until(`notation.length===1`);
    await friendPage.click('#resign');await friendPage.click('#confirm-resign');
    await friendPage.until(`finished!==null`);
    await hostPage.click('[data-view="tournaments"]');await hostPage.click('#tournament-refresh');
    await hostPage.until(`document.querySelector('#tournament-status').textContent.includes('complete')`);
    assert.ok((await hostPage.eval(`document.querySelector('.club-standings tbody').textContent`)).includes('Cup host'));
    assert.equal(await hostPage.eval(`getComputedStyle(document.querySelector('#tournament-setup')).display`),'none');
    assert.equal(await hostPage.eval(`getComputedStyle(document.querySelector('#board-focus')).display`),'none');
    const tournamentShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true},hostPage.sessionId);
    fs.writeFileSync(path.join(folder,'tournaments.png'),Buffer.from(tournamentShot.data,'base64'));
    await a.click('[data-view="tools"]');
    await a.click('#tool-clock-toggle');
    await a.click('#tool-clock-w');
    assert.ok((await a.eval(`document.querySelector('#tool-clock-status').textContent`)).includes('Black is thinking'));
    await a.click('#tool-clock-toggle');
    await a.click('#tool-clock-reset');
    assert.equal(await a.eval(`document.querySelector('#tool-clock-w strong').textContent`),'5:00');
    await a.click('#tool-coordinate-board [aria-label="a1"]');
    assert.ok((await a.eval(`document.querySelector('#tool-square-info').textContent`)).includes('dark square'));
    await a.click('#tool-board-flip');
    assert.equal(await a.eval(`document.querySelector('#tool-coordinate-board button').textContent`),'h1');
    await a.eval(`document.querySelector('#tool-notation-search').value='castle';document.querySelector('#tool-notation-search').dispatchEvent(new Event('input'))`);
    assert.equal(await a.eval(`document.querySelectorAll('#tool-notation-list dt').length`),2);
    await a.eval(`document.querySelector('#tool-notes').value='Protect my queen';document.querySelector('#tool-notes').dispatchEvent(new Event('input'))`);
    assert.equal(await a.eval(`localStorage.getItem('chess-club-notebook')`),'Protect my queen');
    assert.equal(await a.eval(`document.documentElement.scrollWidth<=window.innerWidth`),true,'Tools mobile overflow');
    const toolsShot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true},a.sessionId);
    fs.writeFileSync(path.join(folder,'tools-mobile.png'),Buffer.from(toolsShot.data,'base64'));
    assert.deepEqual(errors,[],'Uncaught browser errors');
    console.log('PASS: eight academy lab activities, hints, results, memory reveal, saved rounds, mobile layout, searchable grouped navigation, mobile menu, saved mistake clinic with assisted scoring and reload persistence, daily practice plans, opening review schedules, backup download/validation/restore, five puzzle difficulty levels and switching, Expert mate-in-two challenges, assisted scoring, mistake limits, stronger Hard tactics, profile editing/persistence/progress/mobile, random coaches, saved preferences, contextual tips, coach practice links, mobile coaches, full move review, worker analysis, custom PGNs, annotated export, alternatives and cancellation, opening room for both sides, favourites, endgame academy, puzzle rush score/timer/leave, mobile rooms, endless learning, piece topics, lesson difficulty, separate learning scores, endless puzzles, difficulty selection, hints/reveal/retry, separate saved scores, glossary filters, checkmate guide links, board arrows (laptop clicks, right-drag, touch taps, colours, circles, drawing undo, flip alignment, clear on move), real Chrome desktop/mobile, puzzle solving, fork continuation, lesson completion, replay, two-player online moves, chat escaping, draw offers, local-game restoration, reconnect, study save/load/delete, PGN/FEN import, candidate moves, and opening training for both colors, watch sources, stream-link validation, favorites, focus mode, mobile player fallback, community posting, replies, likes, reports, moderation, deletion, redesigned navigation, day/night colors, board focus, daily challenge shortcut, achievements, saved game replay, coordinate training, queen favicon, and a complete two-player tournament.');
    console.log('Screenshots: '+folder);
  } finally { ws?.close(); chrome.kill(); await new Promise(resolve=>server.close(resolve)); }
}
main().catch(error=>{console.error(error);process.exitCode=1});
