const pages={
 '/':{title:'Play chess, learn & join friends | Advaced Chess Academy ♛',description:'Play chess with friends, solve puzzles at several difficulty levels, explore interactive lessons, and host a friendly tournament. A chess club for curious young players.'},
 '/about.html':{title:'Start your chess adventure | Advaced Chess Academy ♛',description:'Discover games, puzzles, lessons, friend tournaments, chess tools, and a community for learning together. Find your first activity.'},
 '/chess-extras/index.html':{title:'Chess study room & opening practice | Advaced Chess Academy ♛',description:'Explore chess positions, import FEN and PGN, practice openings, and save your studies in your browser.'},
 '/chess-extras/watch.html':{title:'Watch chess & follow live games | Advaced Chess Academy ♛',description:'Follow the current Lichess TV game, explore chess broadcasts, and save your favorite viewing links.'},
 '/chess-extras/community.html':{title:'Chess questions, tips & community | Advaced Chess Academy ♛',description:'Ask chess questions, share ideas, and celebrate small wins with your club. Community posts are shared on this site.'}
};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function createDiscovery(value=''){
 let origin='';if(value){const u=new URL(value);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.pathname!=='/'||u.search||u.hash)throw Error('PUBLIC_SITE_URL must be the public site origin, such as https://chess.example.com');origin=u.origin}
 return {robots:()=>origin?'User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: '+origin+'/sitemap.xml\n':'User-agent: *\nDisallow: /\n',sitemap:()=>origin?'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+Object.keys(pages).map(p=>'<url><loc>'+escape(origin+p)+'</loc></url>').join('')+'</urlset>':null,
 html(html,path){const key=path==='/david.html'?'/':path,page=pages[key];if(!page)return html;html=html.replace(/<title>[^<]*<\/title>/,'<title>'+escape(page.title)+'</title>').replace(/<meta\s+(?:name="(?:description|twitter:[^"]*)"|property="og:[^"]*")[^>]*>/g,'');let tags=`<meta name="description" content="${escape(page.description)}"><meta property="og:title" content="${escape(page.title)}"><meta property="og:description" content="${escape(page.description)}"><meta property="og:site_name" content="Advaced Chess Academy ♛"><meta property="og:type" content="website"><meta name="twitter:card" content="summary">`;if(origin){tags+=`<link rel="canonical" href="${escape(origin+key)}"><meta property="og:url" content="${escape(origin+key)}">`;const data={'@context':'https://schema.org','@type':'WebSite',name:'Advaced Chess Academy ♛',url:origin+'/',description:pages['/'].description,inLanguage:'en'};tags+='<script type="application/ld+json">'+JSON.stringify(data).replace(/</g,'\\u003c')+'</script>'}else tags+='<meta name="robots" content="noindex">';return html.replace('</head>',tags+'</head>')}
 };
}
module.exports={createDiscovery};
