const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
function createTournaments({dataDir,now,createGame,getGame,ensureCapacity}){
 const file=path.join(dataDir,'tournaments.json');let events=new Map();try{events=new Map(JSON.parse(fs.readFileSync(file,'utf8')))}catch(e){if(e.code!=='ENOENT')throw e}
 const hash=t=>crypto.createHash('sha256').update(t).digest('hex');
 const fail=(message,status=400)=>{throw Object.assign(Error(message),{status})};
 const persist=()=>{fs.writeFileSync(file+'.tmp',JSON.stringify([...events]),{mode:0o600});fs.renameSync(file+'.tmp',file)};
 const name=v=>String(v||'Guest').replace(/[\x00-\x1f\x7f]/g,'').trim().slice(0,32)||'Guest';
 function addPlayer(e,label){if(e.players.length>=8)fail('This tournament is full.',409);const token=crypto.randomBytes(24).toString('hex');const p={id:crypto.randomBytes(6).toString('hex'),name:name(label),key:hash(token)};e.players.push(p);persist();return {p,token}}
 function startRound(e,round=e.rounds[e.round]){for(const m of round){if(m.id)continue;if(m.b===null){m.result='bye';continue}const w=e.players.find(p=>p.id===m.w),b=e.players.find(p=>p.id===m.b);Object.assign(m,createGame(w.name,b.name,e.time))}persist()}
 function refresh(e){if(e.status!=='running')return;let changed=false;for(const m of e.rounds[e.round]){if(m.result)continue;const result=getGame(m.id);if(result){m.result=result.title.startsWith('White')?'1-0':result.title.startsWith('Black')?'0-1':'1/2-1/2';changed=true}}
 if(e.rounds[e.round].every(m=>m.result)){e.round++;if(e.round===e.rounds.length)e.status='finished';else startRound(e);changed=true}if(changed)persist()}
 function snapshot(e,p){refresh(e);const scores=e.players.map(x=>({id:x.id,name:x.name,points:0,played:0,wins:0}));for(const round of e.rounds)for(const m of round){if(!m.result||m.result==='bye')continue;const w=scores.find(x=>x.id===m.w),b=scores.find(x=>x.id===m.b);w.played++;b.played++;w.points+=m.result==='1-0'?1:m.result==='1/2-1/2'?.5:0;b.points+=m.result==='0-1'?1:m.result==='1/2-1/2'?.5:0;if(m.result==='1-0')w.wins++;if(m.result==='0-1')b.wins++}
 scores.sort((a,b)=>b.points-a.points||b.wins-a.wins||a.name.localeCompare(b.name));return {id:e.id,title:e.title,status:e.status,time:e.time,me:p.id,host:e.host===p.id,round:e.round,players:e.players.map(x=>({id:x.id,name:x.name})),standings:scores,rounds:e.rounds.map((round,index)=>round.map(m=>({w:m.w,b:m.b,id:m.id,result:m.result||null,...(index<=e.round&&p.id===m.w&&m.whiteToken?{token:m.whiteToken}:index<=e.round&&p.id===m.b&&m.blackToken?{token:m.blackToken}:{})})))}}
 function handle(req,url,body){const match=url.pathname.match(/^\/api\/tournaments(?:\/([a-f0-9]{12})(?:\/(join|start))?)?$/);if(!match)return {status:404,body:{error:'Not found'}};const [,id,action]=match;
 if(!id&&req.method==='POST'){if(events.size>=100)fail('The tournament limit has been reached.',503);const time=Number(body.time||300);if(![180,300,600,900].includes(time))fail('Choose a supported time control.');const e={id:crypto.randomBytes(6).toString('hex'),title:name(body.title||'Friends cup'),time,createdAt:now(),players:[],rounds:[],round:0,status:'lobby'};events.set(e.id,e);const {p,token}=addPlayer(e,body.name);e.host=p.id;persist();return {status:201,body:{...snapshot(e,p),token}}}
 const e=events.get(id);if(!e)fail('Tournament not found.',404);
 if(action==='join'&&req.method==='POST'){if(e.status!=='lobby')fail('This tournament has already started.',409);const {p,token}=addPlayer(e,body.name);return {status:200,body:{...snapshot(e,p),token}}}
 const token=req.headers.authorization?.replace(/^Bearer /,'')||'',p=e.players.find(p=>p.key===hash(token));if(!p)fail('Your tournament session is not valid.',401);
 if(action==='start'&&req.method==='POST'){if(e.host!==p.id)fail('Only the host can start the tournament.',403);if(e.status!=='lobby')fail('The tournament has already started.',409);if(e.players.length<2)fail('Invite at least one friend first.');ensureCapacity(e.players.length*(e.players.length-1)/2);let order=e.players.map(p=>p.id);if(order.length%2)order.push(null);for(let r=0;r<order.length-1;r++){const matches=[];for(let i=0;i<order.length/2;i++){let a=order[i],b=order[order.length-1-i];if(a===null)[a,b]=[b,a];else if(b!==null&&(r+i)%2)[a,b]=[b,a];matches.push({w:a,b})}e.rounds.push(matches);order.splice(1,0,order.pop())}e.status='running';try{for(const round of e.rounds)startRound(e,round)}catch(error){e.status='lobby';e.rounds=[];persist();throw error}return {status:200,body:snapshot(e,p)}}
 if(!action&&req.method==='GET')return {status:200,body:snapshot(e,p)};fail('Method not allowed.',405)}
 return {handle};
}
module.exports={createTournaments};
